5.1.0.0 (#29) (#30)
* Allow addon to hook the Inventory getting

* bump ver

* New translations messages.json (Dutch)

* Update config.yml

* Bump sqlite-jdbc from 3.34.0 to 3.36.0.3

Bumps [sqlite-jdbc](https://github.com/xerial/sqlite-jdbc) from 3.34.0 to 3.36.0.3.
- [Release notes](https://github.com/xerial/sqlite-jdbc/releases)
- [Changelog](https://github.com/xerial/sqlite-jdbc/blob/master/CHANGELOG)
- [Commits](https://github.com/xerial/sqlite-jdbc/compare/3.34.0...3.36.0.3)

---
updated-dependencies:
- dependency-name: org.xerial:sqlite-jdbc
  dependency-type: direct:development
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Bump okhttp from 4.9.2 to 4.9.3

Bumps [okhttp](https://github.com/square/okhttp) from 4.9.2 to 4.9.3.
- [Release notes](https://github.com/square/okhttp/releases)
- [Changelog](https://github.com/square/okhttp/blob/master/CHANGELOG.md)
- [Commits](https://github.com/square/okhttp/compare/parent-4.9.2...parent-4.9.3)

---
updated-dependencies:
- dependency-name: com.squareup.okhttp3:okhttp
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

* Fix broken readme

* Fix broken readme again

* [FactionUUID] Drop support for 0.5.x and support 0.6.x

* New translations messages.json (English)

* New translations messages.json (Korean)

* Bump paperlib from 1.0.6 to 1.0.7

Bumps [paperlib](https://github.com/PaperMC/PaperLib) from 1.0.6 to 1.0.7.
- [Release notes](https://github.com/PaperMC/PaperLib/releases)
- [Changelog](https://github.com/PaperMC/PaperLib/blob/master/CHANGELOG.md)
- [Commits](https://github.com/PaperMC/PaperLib/compare/1.0.6...v1.0.7)

---
updated-dependencies:
- dependency-name: io.papermc:paperlib
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

* [WorldGuardIntegration] Fix global region issue

* New translations messages.json (Korean)

* Try to fix sync issue

* Fix shade issue

* Change to common-lang3, adapt to spigot 1.18 lib changes

* Revert wrong changes

* Volatile the dev-mode, prevent some issues

* Target to 1.18-rc3

* Remove lombok.NonNull and javax.annotation.Nonnull usage

* Fix auto despawn watcher

* Deprecated DisplayWatcher

* Re-add "Enchantment name shows on enchanted books" feature

* Fix ShopPurger

* Update crowdin.yml

* Fixed a bug in which the Find command would display the result multiple times.

* Fix case-sensitive and underscore issue in enabled languages

* Fix NoClassDefFoundError not handled by catch statement

* Bump junit-jupiter-api from 5.8.1 to 5.8.2

Bumps [junit-jupiter-api](https://github.com/junit-team/junit5) from 5.8.1 to 5.8.2.
- [Release notes](https://github.com/junit-team/junit5/releases)
- [Commits](https://github.com/junit-team/junit5/compare/r5.8.1...r5.8.2)

---
updated-dependencies:
- dependency-name: org.junit.jupiter:junit-jupiter-api
  dependency-type: direct:development
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

* Adapt to 1.18

* Fix item namespace method finding issue, also fix fallback

* Fix caching issue, invalidate cache when getting

* Fix case-sensitive issue in enabled languages

* Switch access token to new one

* Bump IridiumSkyblock from 3.1.2 to 3.2.2

Bumps IridiumSkyblock from 3.1.2 to 3.2.2.

---
updated-dependencies:
- dependency-name: com.iridium:IridiumSkyblock
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* #16 Try to fix cache method issue

* Delete incorrect reloaction

* Fix mistaken on update message

* Fix price command bypassing the integer only option.

* Bump advanced-region-market from 3.3.5 to 3.3.6

Bumps advanced-region-market from 3.3.5 to 3.3.6.

---
updated-dependencies:
- dependency-name: com.github.alex9849:advanced-region-market
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

* Bump SongodaCore from 2.5.14 to 2.6.3

Bumps SongodaCore from 2.5.14 to 2.6.3.

---
updated-dependencies:
- dependency-name: com.songoda:SongodaCore
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* Fix #20, correct the event using

* Fix #17

* Change misleading configuration description

* Backport for NPE fix

* Don't use SimplixStorage

* Refactor new language system [1/3]
preparing local language files

* Fix color issue with certain input

* Fix testing and bump spigot-api to 1.18.1-R0.1-SNAPSHOT

* Fix test

* Fix comment missing issue, implement itself comment updater

* Delete backup when update successful

* Handle local files loading

* Fix plugin loading stuck on i18n loading

* Printing errors when cannot create column

* Fix misleading message and apply tradeAllWord to trade message

* Fix NoSuchFileException

* Loading bundled file for not internet connection

* Language System improvement
Let cachedGameLanguageCode only caching default one
Fix stuck loading issue for textManager
Add related languages code matching, Fix #1

* Update languagesCache only when no cache

* Fix misleading sell messages

* Fix misleading sell messages

* Try to fix crowdin issue

* Update Crowdin configuration file

* Try to fix crowdin issue again

* New translations messages.json (Romanian)

* New translations messages.json (Dutch)

* New translations messages.json (Portuguese, Brazilian)

* New translations messages.json (Vietnamese)

* New translations messages.json (English)

* New translations messages.json (Chinese Traditional)

* New translations messages.json (Chinese Simplified)

* New translations messages.json (Ukrainian)

* New translations messages.json (Turkish)

* New translations messages.json (Swedish)

* New translations messages.json (Serbian (Cyrillic))

* New translations messages.json (Russian)

* New translations messages.json (Portuguese)

* New translations messages.json (Polish)

* New translations messages.json (Norwegian)

* New translations messages.json (Korean)

* New translations messages.json (French)

* New translations messages.json (Japanese)

* New translations messages.json (Italian)

* New translations messages.json (Hungarian)

* New translations messages.json (Hebrew)

* New translations messages.json (Finnish)

* New translations messages.json (Greek)

* New translations messages.json (German)

* New translations messages.json (Danish)

* New translations messages.json (Czech)

* New translations messages.json (Catalan)

* New translations messages.json (Arabic)

* New translations messages.json (Afrikaans)

* New translations messages.json (Spanish)

* New translations messages.json (Chinese Traditional, Hong Kong)

* Only apply right language-version for client

* Fix local file not loading and language not matching

* Update README.md

* Fix local file UTF-8 issue

* Fix broken potion effect

* New Crowdin updates (#28)

* Update source file messages.json

* New translations messages.json (Chinese Simplified)

* New translations messages.json (Swedish)

* New translations messages.json (Romanian)

* New translations messages.json (Dutch)

* New translations messages.json (Portuguese, Brazilian)

* New translations messages.json (Vietnamese)

* New translations messages.json (English)

* New translations messages.json (Chinese Traditional)

* New translations messages.json (Chinese Simplified)

* New translations messages.json (Ukrainian)

* New translations messages.json (Turkish)

* New translations messages.json (Swedish)

* New translations messages.json (Serbian (Cyrillic))

* New translations messages.json (Russian)

* New translations messages.json (Portuguese)

* New translations messages.json (Polish)

* New translations messages.json (Norwegian)

* New translations messages.json (Korean)

* New translations messages.json (French)

* New translations messages.json (Japanese)

* New translations messages.json (Italian)

* New translations messages.json (Hungarian)

* New translations messages.json (Hebrew)

* New translations messages.json (Finnish)

* New translations messages.json (Greek)

* New translations messages.json (German)

* New translations messages.json (Danish)

* New translations messages.json (Czech)

* New translations messages.json (Catalan)

* New translations messages.json (Arabic)

* New translations messages.json (Afrikaans)

* New translations messages.json (Spanish)

* New translations messages.json (Chinese Traditional, Hong Kong)

* Fix broken potion effect again

* Add missed findRelativeLanguages

* Deleted getContributors which not supported by 1.15

* Bump to 5.1.0.0

Co-authored-by: Ghost_chu <2908803755@qq.com>
Co-authored-by: Ghost_chu <30802565+Ghost-chu@users.noreply.github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: nikomaru <76208219+nlkomaru@users.noreply.github.com>
Co-authored-by: Warrior <50800980+Warriorrrr@users.noreply.github.com>

Co-authored-by: Ghost_chu <30802565+Ghost-chu@users.noreply.github.com>
Co-authored-by: Ghost_chu <2908803755@qq.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: nikomaru <76208219+nlkomaru@users.noreply.github.com>
Co-authored-by: Warrior <50800980+Warriorrrr@users.noreply.github.com>